-- CreateTable
CREATE TABLE `Budjet` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `titre` VARCHAR(70) NOT NULL,
    `amount` DOUBLE NOT NULL,
    `creatAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updateAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
